# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('goodName', models.CharField(max_length=20)),
                ('goodPrice', models.FloatField(max_length=30)),
                ('goodDesc', models.CharField(max_length=50)),
                ('goodThumb', models.URLField(max_length=50)),
            ],
        ),
    ]
