# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_name', models.CharField(max_length=20, verbose_name='\u5546\u54c1\u540d')),
                ('good_price', models.FloatField(max_length=30, verbose_name='\u552e\u4ef7')),
                ('good_purchase_price', models.FloatField(max_length=1000, verbose_name='\u8fdb\u8d27\u4ef7')),
                ('good_thumb', models.ImageField(upload_to='goodthumb', verbose_name='\u56fe\u7247')),
            ],
            options={
                'db_table': 'b_good_t',
                'verbose_name_plural': '\u5546\u54c1',
            },
        ),
    ]
